services:
  nahora-backend:
    build: ./nahora-backend
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/nahora
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
  nahora-merchant:
    build: ./nahora-merchant
    ports:
      - "3000:3000"
    depends_on:
      - nahora-backend
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  mongodb_data: